[platformio]
default_envs = sensor, actuador

[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:sensor]
build_src_filter =
    +<cliente/main.cpp>
    +<cliente/ClienteTCP.cpp>
    +<cliente/SensorUltrasonico.cpp>

[env:actuador]
build_src_filter =
    +<cliente/PrincipalActuador.cpp>
    +<cliente/ClienteTCP.cpp>
    +<cliente/IndicadorLeds.cpp>
